name: Rematch Book Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - "*"

jobs:
  testing:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('yarn.lock') }}
            yarn

      - name: Install
        run: yarn install --frozen-lockfile --pure-lockfile

      - name: Build & Testing
        run: |
          yarn test
          yarn tsc
          yarn lint
          yarn build
